apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secrets.name }}
  namespace: {{ $.Values.namespace }}
  labels:
{{- range $labK, $labV := .Values.labels }}
    {{ $labK }}: {{ $labV }}
{{- end }}
    instance: {{ uuidv4 | quote }}
type: Opaque
data:
{{- range $secK, $secV := .Values.secrets.inline }}
    {{ $secK }}: {{ $secV }}
{{- end }}